Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end

  # controller server, should install the ansible
  config.vm.define "controller" do |app|
    app.vm.hostname = "controller"
    app.vm.box = "bento/ubuntu-16.04"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.vm.network "private_network", ip: "10.10.10.100"
    app.vm.provision :shell, path: 'controller.sh' # only simple setting
  end

  config.vm.define "app1" do |app|
    app.vm.hostname = "app1"
    app.vm.box = "bento/ubuntu-16.04"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.vm.network "private_network", ip: "10.10.10.101"
    app.vm.provision :shell, path: 'app.sh' # only simple setting
  end

  config.vm.define "app2" do |app|
    app.vm.hostname = "app2"
    app.vm.box = "bento/ubuntu-16.04"
    app.vm.box_check_update = false
    app.ssh.insert_key = false
    app.vm.network "private_network", ip: "10.10.10.102"
    app.vm.provision :shell, path: 'app.sh' # only simple setting
  end

end
