---
- hosts: all
  sudo: yes
  vars:
    ip: "192.168.122.30/24"
    name: test
    password: test
  tasks:
    - name: Install pip
      package:
        name: python-pip
        state: latest
    - name: Install lxc
      package:
        name: lxc
        state: latest
    - name: Install lxc-dev
      package:
        name: lxc-dev
        state: latest
    - name: Install lxc-python2
      pip:
        name: lxc-python2
    - name: Create a started container
      lxc_container:
        name: "{{ name }}"
        container_log: true
        template: ubuntu
        state: started
        template_options: --release trusty
